[common]
platform = nordicnrf52@10.11.0
framework = arduino
extra_scripts = post:generate_uf2.py
board_build.bsp.name = adafruit
board_build.variants_dir = variants
platform_packages =
    platformio/framework-arduinoadafruitnrf52

[env:nicenano]
extends = common
board = nicenano

[env:holyiot]
extends = common
board = holyiot_nrf52840_usb
build_flags = -DBOARD_LED_PIN=6
